### ISSUE TITLE
horizontal line 

### ISSUE THREAD

**Issue by kotamine** [kotamine/RobotParlor#3]
Neither hr() nor  HTML("<hr>")  is working. I think it has to do with  shinydashboard structure. 
Please help me fix it.

**Comment by airtonjr** [comment]
Use "tags$hr()"
The CSS is already online.

**Comment by kotamine** [comment]
Hey I cannot find the code for this. Could you commit it again?

**Comment by airtonjr** [comment]
Yes, I just did it. Try and see if is good to close the issue.

**Comment by airtonjr** [comment]
@kotamine Update your files with my new sync.
